# Generated by Django 4.1.5 on 2023-01-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='lang',
            field=models.CharField(default='es', max_length=5),
            preserve_default=False,
        ),
    ]
