# Generated by Django 4.1.5 on 2023-02-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo_email_verified_userinfo_verify_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
