# Generated by Django 4.1.5 on 2023-02-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userinfo_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='balance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
