# Generated by Django 4.1.5 on 2023-01-23 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=40)),
                ('stripe_plan_id', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=10)),
                ('collection_method', models.CharField(max_length=40)),
                ('start_date', models.DateTimeField()),
                ('billing_cycle_anchor', models.DateTimeField()),
                ('trial_start', models.DateTimeField(blank=True)),
                ('trial_end', models.DateTimeField(blank=True)),
                ('current_period_end', models.DateTimeField(blank=True)),
                ('current_period_start', models.DateTimeField(blank=True)),
                ('cancel_at', models.DateTimeField(blank=True)),
                ('canceled_at', models.DateTimeField(blank=True)),
                ('ended_at', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
