# Generated by Django 4.1.5 on 2023-01-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plan_collection_method_remove_plan_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='id',
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_subscription_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
