# Generated by Django 4.1.5 on 2023-02-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plan_lookup_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='stripe_plan_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='unit_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
