# Generated by Django 4.1.5 on 2023-02-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_remove_plan_stripe_plan_id_plan_unit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='interval',
            field=models.CharField(default='month', max_length=30),
            preserve_default=False,
        ),
    ]
