# Generated by Django 4.1.5 on 2023-02-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_plan_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='mxn', max_length=15),
            preserve_default=False,
        ),
    ]
