# Generated by Django 4.1.5 on 2023-02-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_plan_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='active',
        ),
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.CharField(default='active', max_length=30),
            preserve_default=False,
        ),
    ]
