# Generated by Django 4.1.5 on 2023-02-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='language',
            field=models.CharField(default='es', max_length=5),
        ),
    ]
